services:
  postgres:
    image: 'postgres:latest'
    container_name: 'GestionStock'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=stockGestion'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'

  adminer:
    image: adminer
    container_name: adminer_gestion
    restart: always
    ports:
      - 8083:8080